# Generated by Django 4.0.5 on 2022-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
