version: '3.3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/staticfiles
    environment:
      PYTHONUNBUFFERED: 0 # preventing print messages to show up
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:1337
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/staticfiles

volumes:
  postgres_data:
  static_volume: