# Generated by Django 4.0.5 on 2022-06-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_link_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='status',
            new_name='activate',
        ),
    ]
